openapi: 3.0.0
info:
  title: Module 2 Content Generation API
  description: API for generating, managing and organizing Module 2 content for the AI textbook
  version: 1.0.0
servers:
  - url: https://api.my-ai-book.com/v1
    description: Production server
  - url: https://staging-api.my-ai-book.com/v1
    description: Staging server

paths:
  /modules/2/contents:
    get:
      summary: List all Module 2 content
      description: Retrieve a list of all Module 2 content with filtering and pagination options
      parameters:
        - name: status
          in: query
          description: Filter by content status (draft, under_review, approved, published)
          required: false
          schema:
            type: string
            enum: [draft, under_review, approved, published]
        - name: contentType
          in: query
          description: Filter by content type (lesson, chapter, exercise, example)
          required: false
          schema:
            type: string
            enum: [lesson, chapter, exercise, example]
        - name: authorId
          in: query
          description: Filter by author ID
          required: false
          schema:
            type: string
        - name: chapterNumber
          in: query
          description: Filter by chapter number
          required: false
          schema:
            type: integer
        - name: limit
          in: query
          description: Number of results per page
          required: false
          schema:
            type: integer
            default: 20
            maximum: 100
        - name: offset
          in: query
          description: Offset for pagination
          required: false
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of Module 2 content
          content:
            application/json:
              schema:
                type: object
                properties:
                  contents:
                    type: array
                    items:
                      $ref: '#/components/schemas/Content'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '400':
          description: Invalid parameters
        '401':
          description: Unauthorized
      security:
        - bearerAuth: []
    post:
      summary: Create new Module 2 content
      description: Create a new piece of Module 2 content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContentInput'
      responses:
        '201':
          description: Content created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Content'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
        - bearerAuth: []

  /modules/2/contents/{contentId}:
    get:
      summary: Get specific Module 2 content
      description: Retrieve a specific piece of Module 2 content by its ID
      parameters:
        - name: contentId
          in: path
          required: true
          description: ID of the content to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Content retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Content'
        '404':
          description: Content not found
        '401':
          description: Unauthorized
      security:
        - bearerAuth: []
    put:
      summary: Update Module 2 content
      description: Update an existing piece of Module 2 content
      parameters:
        - name: contentId
          in: path
          required: true
          description: ID of the content to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContentInput'
      responses:
        '200':
          description: Content updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Content'
        '400':
          description: Invalid input
        '404':
          description: Content not found
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
        - bearerAuth: []
    delete:
      summary: Delete Module 2 content
      description: Delete a specific piece of Module 2 content
      parameters:
        - name: contentId
          in: path
          required: true
          description: ID of the content to delete
          schema:
            type: string
      responses:
        '204':
          description: Content deleted successfully
        '404':
          description: Content not found
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
        - bearerAuth: []

  /modules/2/contents/{contentId}/status:
    put:
      summary: Update content status
      description: Update the status of a content item (for workflow management)
      parameters:
        - name: contentId
          in: path
          required: true
          description: ID of the content
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [draft, under_review, approved, published]
                  description: New status
                comment:
                  type: string
                  description: Optional comment about the status change
              required:
                - status
      responses:
        '200':
          description: Status updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Content'
        '400':
          description: Invalid status or input
        '404':
          description: Content not found
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
        - bearerAuth: []

  /modules/2/chapters:
    get:
      summary: List all Module 2 chapters
      description: Retrieve all chapters in Module 2
      responses:
        '200':
          description: List of Module 2 chapters
          content:
            application/json:
              schema:
                type: object
                properties:
                  chapters:
                    type: array
                    items:
                      $ref: '#/components/schemas/Chapter'
        '401':
          description: Unauthorized
      security:
        - bearerAuth: []

  /modules/2/assessments:
    get:
      summary: List all Module 2 assessments
      description: Retrieve all assessments for Module 2
      parameters:
        - name: contentId
          in: query
          description: Filter by associated content ID
          required: false
          schema:
            type: string
        - name: type
          in: query
          description: Filter by assessment type (quiz, project, hands-on)
          required: false
          schema:
            type: string
            enum: [quiz, project, hands-on]
      responses:
        '200':
          description: List of Module 2 assessments
          content:
            application/json:
              schema:
                type: object
                properties:
                  assessments:
                    type: array
                    items:
                      $ref: '#/components/schemas/Assessment'
        '401':
          description: Unauthorized
      security:
        - bearerAuth: []
    post:
      summary: Create new assessment
      description: Create a new assessment for Module 2 content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssessmentInput'
      responses:
        '201':
          description: Assessment created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Assessment'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
        - bearerAuth: []

  /users/{userId}/role:
    put:
      summary: Update user role
      description: Update a user's role in the system
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the user
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                role:
                  type: string
                  enum: [student, author, editor, admin]
                  description: New role for the user
              required:
                - role
      responses:
        '200':
          description: User role updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid role
        '404':
          description: User not found
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
        - bearerAuth: []

components:
  schemas:
    Content:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier
        title:
          type: string
          description: Title of the content piece
        content:
          type: string
          description: Markdown content
        contentType:
          type: string
          enum: [lesson, chapter, exercise, example]
          description: Type of content
        authorId:
          type: string
          description: Reference to author
        reviewerId:
          type: string
          description: Reference to reviewer (optional)
        status:
          type: string
          enum: [draft, under_review, approved, published]
          description: Current status
        createdAt:
          type: string
          format: date-time
          description: Creation timestamp
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp
        version:
          type: integer
          description: Version number
        learningObjectives:
          type: array
          items:
            type: string
          description: Specific skills/concepts
        prerequisites:
          type: array
          items:
            type: string
          description: Required knowledge
        handsOnExamples:
          type: array
          items:
            type: object
            properties:
              title:
                type: string
              description:
                type: string
              code:
                type: string
          description: Interactive examples
        assessments:
          type: array
          items:
            $ref: '#/components/schemas/Assessment'
          description: Associated assessments
        chapterNumber:
          type: integer
          description: Chapter number this content belongs to
      required:
        - id
        - title
        - content
        - contentType
        - authorId
        - status
        - createdAt
        - updatedAt
        - version

    ContentInput:
      type: object
      properties:
        title:
          type: string
          description: Title of the content piece
        content:
          type: string
          description: Markdown content
        contentType:
          type: string
          enum: [lesson, chapter, exercise, example]
          description: Type of content
        learningObjectives:
          type: array
          items:
            type: string
          description: Specific skills/concepts
        prerequisites:
          type: array
          items:
            type: string
          description: Required knowledge
        handsOnExamples:
          type: array
          items:
            $ref: '#/components/schemas/HandsOnExample'
          description: Interactive examples
        chapterNumber:
          type: integer
          description: Chapter number this content belongs to (1-5)
      required:
        - title
        - content
        - contentType
        - chapterNumber

    Chapter:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier
        title:
          type: string
          description: Title of the chapter
        moduleNumber:
          type: integer
          description: Module number (should be 2)
        chapterNumber:
          type: integer
          description: Chapter number (1-5)
        chapterTitle:
          type: string
          enum: [Introduction to Digital Twins, Gazebo Fundamentals, Unity Robotics Simulation, ROS 2 Integration with Simulation, Hands-on Labs & Troubleshooting]
          description: Title of the chapter
        contentIds:
          type: array
          items:
            type: string
          description: IDs of content in this chapter
        learningObjectives:
          type: array
          items:
            type: string
          description: Learning objectives for this chapter
        estimatedTime:
          type: integer
          description: Estimated time to complete in minutes
      required:
        - id
        - title
        - moduleNumber
        - chapterNumber
        - chapterTitle
        - contentIds

    Assessment:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier
        type:
          type: string
          enum: [quiz, project, hands-on]
          description: Type of assessment
        question:
          type: string
          description: The assessment question
        options:
          type: array
          items:
            type: string
          description: Options for multiple choice
        correctAnswer:
          type: array
          items:
            type: string
          description: Correct answer(s)
        explanation:
          type: string
          description: Explanation of the correct answer
        associatedContentId:
          type: string
          description: Content this assessment tests
      required:
        - id
        - type
        - question
        - associatedContentId

    AssessmentInput:
      type: object
      properties:
        type:
          type: string
          enum: [quiz, project, hands-on]
          description: Type of assessment
        question:
          type: string
          description: The assessment question
        options:
          type: array
          items:
            type: string
          description: Options for multiple choice
        correctAnswer:
          type: array
          items:
            type: string
          description: Correct answer(s)
        explanation:
          type: string
          description: Explanation of the correct answer
        associatedContentId:
          type: string
          description: Content this assessment tests
      required:
        - type
        - question
        - associatedContentId

    HandsOnExample:
      type: object
      properties:
        title:
          type: string
          description: Title of the example
        description:
          type: string
          description: Description of the example
        code:
          type: string
          description: Code for the example
        prerequisites:
          type: array
          items:
            type: string
          description: Software/prerequisites needed
      required:
        - title
        - description
        - code

    User:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier
        username:
          type: string
          description: User's username
        email:
          type: string
          format: email
          description: User's email
        role:
          type: string
          enum: [student, author, editor, admin]
          description: User's role in the system
        createdAt:
          type: string
          format: date-time
          description: User account creation timestamp
        lastLogin:
          type: string
          format: date-time
          description: Timestamp of last login
      required:
        - id
        - username
        - email
        - role
        - createdAt

    Pagination:
      type: object
      properties:
        limit:
          type: integer
          description: Number of items per page
        offset:
          type: integer
          description: Current offset
        total:
          type: integer
          description: Total number of items
        totalPages:
          type: integer
          description: Total number of pages
        currentPage:
          type: integer
          description: Current page number

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []